In [1]:
# ติดตั้ง library เพิ่มเติม (ถ้าจำเป็น)
!pip install plotly kaleido -q

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

#ดาวน์โหลดฟอนต์ภาษาไทย (TH Sarabun New)
!wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf
#เพิ่มฟอนต์เข้าไปในระบบ
mpl.font_manager.fontManager.addfont('thsarabunnew-webfont.ttf')
mpl.rc('font', family='TH Sarabun New', size=16)
sns.set_theme(style="whitegrid", font="TH Sarabun New")

# ตั้งค่า style
plt.rcParams['figure.dpi'] = 120

print('✅ Import สำเร็จ! พร้อมวิเคราะห์ข้อมูลแล้ว 🚀')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 2.1 MB/s eta 0:00:00
✅ Import สำเร็จ! พร้อมวิเคราะห์ข้อมูลแล้ว 🚀

In [2]:
# ใช้ URL มาเพื่อโหลดไฟล์
file_url = 'https://storagepracticebdidev.blob.core.windows.net/dev-uploads/app/bdi/uploads1-9-20260312-162658503.csv?sv=2026-02-06&st=2026-03-12T09%3A26%3A58Z&se=2028-12-06T09%3A26%3A58Z&sr=b&sp=r&sig=fV6wspFvE9dTgkzY9xLbZ%2FXP4i%2B%2FN0BliGZAx9%2Bzywo%3D'
df_elec = pd.read_csv(file_url, encoding='utf-8-sig')
print('✅ โหลดไฟล์ electric.csv จาก URL สำเร็จแล้ว')


print('=' * 60)
print('📅 ข้อมูลสถิติหน่วยจำหน่ายไฟฟ้าแยกตามเขต')
print(f'   ➜ จำนวนแถว: {df_elec.shape[0]:,} แถว | คอลัมน์: {df_elec.shape[1]} คอลัมน์')
print(f'   ➜ คอลัมน์: {df_elec.columns.tolist()}')
print('=' * 60)

print()
print('🔍 ตัวอย่างสถิติหน่วยจำหน่ายไฟฟ้าแยกตามเขต:')
display(df_elec)

✅ โหลดไฟล์ electric.csv จาก URL สำเร็จแล้ว
============================================================
📅 ข้อมูลสถิติหน่วยจำหน่ายไฟฟ้าแยกตามเขต
   ➜ จำนวนแถว: 83 แถว | คอลัมน์: 21 คอลัมน์
   ➜ คอลัมน์: ['ปี', 'เดือน', ' วัดเลียบ ', ' คลองเตย ', ' ยานนาวา ', ' บางกะปิ ', ' มีนบุรี ', ' สมุทรปราการ ', ' บางพลี ', ' สามเสน ', ' นนทบุรี ', ' บางใหญ่ ', ' ธนบุรี ', ' ราษฎร์บูรณะ ', ' บางขุนเทียน ', ' บางเขน ', ' บางนา ', ' บางบัวทอง ', ' ลาดกระบัง ', ' นวลจันทร์ ', '(หักไฟทำการ)']
============================================================

🔍 ตัวอย่างสถิติหน่วยจำหน่ายไฟฟ้าแยกตามเขต:

,ปี,เดือน,วัดเลียบ,คลองเตย,ยานนาวา,บางกะปิ,มีนบุรี,สมุทรปราการ,บางพลี,สามเสน,...,บางใหญ่,ธนบุรี,ราษฎร์บูรณะ,บางขุนเทียน,บางเขน,บางนา,บางบัวทอง,ลาดกระบัง,นวลจันทร์,(หักไฟทำการ)
0,2562.0,ม.ค.,93.96,375.86,154.62,243.49,156.70,400.83,409.56,291.46,...,134.90,152.69,321.13,199.88,239.95,220.28,146.70,152.37,150.26,"4,119.31"
1,NaN,ก.พ.,94.88,373.54,156.55,248.90,161.21,396.36,408.68,298.58,...,142.73,158.55,314.98,202.95,254.82,222.29,152.47,155.39,158.49,"4,188.50"
2,NaN,มี.ค.,103.27,412.09,170.67,272.89,180.84,445.57,458.59,328.44,...,159.21,174.84,361.92,225.96,281.99,246.60,172.70,167.90,174.00,"4,660.94"
3,NaN,เม.ย.,108.59,419.71,179.36,293.99,188.01,400.70,426.82,345.59,...,173.20,187.59,338.99,224.96,295.08,255.97,176.43,172.99,187.62,"4,709.44"
4,NaN,พ.ค.,110.97,429.76,184.89,307.18,195.85,446.77,468.74,355.00,...,176.45,193.47,368.12,243.04,307.90,268.79,186.15,194.68,193.52,"4,976.37"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,NaN,ก.ค.,97.02,419.06,171.30,295.84,197.27,421.38,482.65,328.03,...,181.01,188.45,322.13,222.60,306.31,269.26,216.13,177.19,173.98,"4,800.15"
79,NaN,ส.ค.,98.48,429.89,170.95,305.49,199.75,414.64,485.13,336.91,...,185.54,193.74,319.74,225.90,313.56,274.17,219.57,188.20,179.39,"4,881.46"
80,NaN,ก.ย.,92.91,408.87,163.69,287.20,188.05,410.30,475.33,318.31,...,172.17,181.35,309.14,213.33,289.19,262.69,207.16,174.44,164.13,"4,635.66"
81,NaN,ต.ค.,91.96,413.57,162.70,284.44,187.98,411.02,472.91,314.98,...,171.22,178.09,315.09,211.28,292.78,259.38,211.05,174.31,163.81,"4,635.88"
82,NaN,พ.ย.,83.89,377.38,146.88,259.04,168.83,385.53,440.58,281.23,...,152.23,161.61,286.31,193.76,260.92,235.14,191.53,162.62,146.24,"4,224.75"

In [3]:
#เติมเลขปีใน column ปี เเละเปลี่ยน datatype เป็น int
df_elec['ปี'] = df_elec['ปี'].ffill()
df_elec['ปี'] = df_elec['ปี'].astype(int)

print('✅ เติมข้อมูลในคอลัมน์ \'ปี\' สำเร็จแล้ว')
print('\n🔍 ตัวอย่างข้อมูลหลังเติมปี:')
display(df_elec[['ปี','(หักไฟทำการ)']])

✅ เติมข้อมูลในคอลัมน์ 'ปี' สำเร็จแล้ว

🔍 ตัวอย่างข้อมูลหลังเติมปี:

      ปี (หักไฟทำการ)
0   2562     4,119.31
1   2562     4,188.50
2   2562     4,660.94
3   2562     4,709.44
4   2562     4,976.37
..   ...          ...
78  2568     4,800.15
79  2568     4,881.46
80  2568     4,635.66
81  2568     4,635.88
82  2568     4,224.75

[83 rows x 2 columns]

In [4]:
#เปลี่ยน datatype ค่าหักไฟทำการเป็น float
df_elec['(หักไฟทำการ)'] = df_elec['(หักไฟทำการ)'].str.replace(',', '', regex=False).astype(float)
df_elec['(หักไฟทำการ)'].dtype

dtype('float64')

In [5]:
# 1. ทำความสะอาดชื่อคอลัมน์ โดยลบช่องว่างนำหน้า/ต่อท้าย
df_elec.columns = df_elec.columns.str.strip()

# 2. สร้างคอลัมน์ 'Month_num' จากชื่อเดือนภาษาไทยเเละลบช่องที่เว้นว่างในเดือน
month_mapping = {
    'ม.ค.': 1, 'ก.พ.': 2, 'มี.ค.': 3, 'เม.ย.': 4, 'พ.ค.': 5, 'มิ.ย.': 6,
    'ก.ค.': 7, 'ส.ค.': 8, 'ก.ย.': 9, 'ต.ค.': 10, 'พ.ย.': 11, 'ธ.ค.': 12
}
df_elec['Month_num'] = df_elec['เดือน'].str.strip().map(month_mapping)
display(df_elec[['ปี','Month_num']])

      ปี  Month_num
0   2562          1
1   2562          2
2   2562          3
3   2562          4
4   2562          5
..   ...        ...
78  2568          7
79  2568          8
80  2568          9
81  2568         10
82  2568         11

[83 rows x 2 columns]

In [6]:

# 3. สร้างคอลัมน์ 'Date' ในรูปแบบ datetime โดยแปลงปีพุทธศักราชเป็นคริสต์ศักราชชั่วคราวเพื่อสร้างวันที่
df_elec['Date'] = pd.to_datetime((df_elec['ปี'].astype(int) - 543).astype(str) + '-' + df_elec['Month_num'].astype(int).astype(str) + '-01')

print('✅ การเตรียมข้อมูลสำเร็จแล้ว')
print('\n🔍 ตัวอย่างข้อมูลหลังจากเตรียม:')
display(df_elec[['Date', '(หักไฟทำการ)']])

✅ การเตรียมข้อมูลสำเร็จแล้ว

🔍 ตัวอย่างข้อมูลหลังจากเตรียม:

         Date  (หักไฟทำการ)
0  2019-01-01       4119.31
1  2019-02-01       4188.50
2  2019-03-01       4660.94
3  2019-04-01       4709.44
4  2019-05-01       4976.37
..        ...           ...
78 2025-07-01       4800.15
79 2025-08-01       4881.46
80 2025-09-01       4635.66
81 2025-10-01       4635.88
82 2025-11-01       4224.75

[83 rows x 2 columns]

### 🔎1. การใช้ไฟฟ้ารวมเปลี่ยนแปลงอย่างไรใน 7 ปี?

จากกราฟด้านล่าง สังเกตได้ในสิ่งเหล่านี้:

1.  **แนวโน้มทั่วไป**: มีแนวโน้มเพิ่มขึ้นหรือลดลงตลอดช่วงเวลาหรือไม่?
2.  **รูปแบบฤดูกาล**: ทุกๆ ปีมีการใช้ไฟฟ้าสูงสุดและต่ำสุดในช่วงเดือนใดบ้าง? (เช่น อาจจะสูงขึ้นช่วงเดือนเมษายน-พฤษภาคม เนื่องจากอากาศร้อน)
3.  **จุดผิดปกติ (Anomalies)**: มีเดือนไหนที่ปริมาณการใช้ไฟฟ้าพุ่งสูงขึ้นหรือลดลงอย่างกะทันหัน ซึ่งแตกต่างจากรูปแบบปกติอย่างชัดเจนหรือไม่?

In [7]:
fig = px.line(
    df_elec,
    x='Date',
    y='(หักไฟทำการ)',
    title='แนวโน้มค่าหักไฟทำการรายเดือน',
    labels={
        'Date': 'วัน/เดือน/ปี',
        '(หักไฟทำการ)': 'ปริมาณค่าหักไฟทำการ (GWh)'
    },
    height=500
)

fig.update_xaxes(dtick="M12", tickformat="%Y", hoverformat="%b %Y")
# ลบการตั้งค่า dtick บนแกน Y เพื่อให้ Plotly ปรับสเกลอัตโนมัติและแสดงผลการขึ้นลงของข้อมูล
# fig.update_yaxes(dtick=500)
fig.update_layout(hovermode="x unified")
fig.show()

จากกราฟแนวโน้มค่าหักไฟทำการรายเดือน (ซึ่งแสดงปริมาณการใช้ไฟฟ้า) สามารถสังเกตและตีความจุดที่น่าสนใจที่เกี่ยวข้องกับเหตุการณ์เหล่านี้ได้ดังนี้:


**1.   ช่วงการระบาดของ COVID-19 (ประมาณปลายปี 2019 ถึง 2021)**: ในช่วง**ปี 2020-2021** คุณอาจจะเห็นการเปลี่ยนแปลงที่ไม่ปกติจากแนวโน้มปกติ เช่น ปริมาณการใช้ไฟฟ้าที่ลดลงอย่างเห็นได้ชัดในบางช่วง (เช่น ช่วงที่มีการล็อกดาวน์หรือปิดสถานประกอบการ) หรืออาจมีการเปลี่ยนแปลงในรูปแบบการใช้ไฟฟ้าภายในบ้านที่เพิ่มขึ้น เนื่องจากคนส่วนใหญ่ทำงานจากที่บ้าน ทำให้เส้นกราฟช่วง**ปี 2020-2021** ลดต่ำลง

**2.   ช่วงคลื่นความร้อน:** โดยปกติแล้ว ประเทศไทยจะมีอากาศร้อนจัดในช่วงเดือน**มีนาคม-พฤษภาคม** ซึ่งทำให้ปริมาณการใช้ไฟฟ้าสูงขึ้นเนื่องจากการเปิดเครื่องปรับอากาศ หากในปีใดมี 'คลื่นความร้อน' ที่รุนแรงกว่าปกติ จะเห็นจุดสูงสุด (Peak) ของการใช้ไฟฟ้าในเดือนเหล่านี้ สูงกว่าค่าเฉลี่ยหรือสูงสุดเป็นพิเศษเมื่อเทียบกับช่วงเวลาเดียวกันในปีก่อนๆ

**3.   ช่วงมาตรการหรือนโยบายของรัฐ:** การเปลี่ยนแปลงนโยบายของรัฐ เช่น นโยบายกระตุ้นเศรษฐกิจ นโยบายประหยัดพลังงาน หรือการปรับค่าไฟฟ้า อาจส่งผลให้เกิดการเปลี่ยนแปลงในกราฟอย่างกะทันหัน หรือมีผลต่อเนื่องเป็นระยะเวลาหนึ่ง
ตัวอย่าง:  
*   หากมีนโยบายส่งเสริมการประหยัดพลังงาน อาจเห็นแนวโน้มการใช้ไฟฟ้าชะลอตัวลง หรือลดลงในช่วงหลังจากมีมาตรการนั้น
*   มาตรการกระตุ้นเศรษฐกิจที่ทำให้กิจกรรมทางธุรกิจเพิ่มขึ้น ก็อาจเห็นปริมาณการใช้ไฟฟ้าสูงขึ้นได้

### 🔎2. เขตไหนใช้ไฟมากที่สุด และใครโตเร็วที่สุด?

จากกราฟด้านล่าง สังเกตได้ถึงสิ่งเหล่านี้:

1.  **ปริมาณการใช้ไฟฟ้า**: เเต่ละเขตมีการใช้ปริมาณมากน้อยเเค่ไหน ในช่วงเวลาไหนบ้าง?
2.  **อัตราการเติบโตของการใช้ไฟฟ้า**: เเต่ละเขตมีอัตราการเติบโตของการใช้ไฟฟ้าที่มากขึ้น หรือน้อยลงโดยเปรียบเทียบปีแรก (2562) และปีสุดท้าย (2567) ที่ข้อมูลครบล่าสุด จากการใช้ไฟฟ้าทั้งหมดของเเต่ละเขต

In [8]:
# 1. กำหนดคอลัมน์ของเขตการจำหน่ายไฟฟ้าทั้ง 18 เขต
district_cols = ['วัดเลียบ', 'คลองเตย', 'ยานนาวา', 'บางกะปิ', 'มีนบุรี', 'สมุทรปราการ', 'บางพลี', 'สามเสน', 'นนทบุรี', 'บางใหญ่', 'ธนบุรี', 'ราษฎร์บูรณะ', 'บางขุนเทียน', 'บางเขน', 'บางนา', 'บางบัวทอง', 'ลาดกระบัง', 'นวลจันทร์']

# 2. คำนวณปริมาณการใช้ไฟฟ้าทั้งหมด (Total Consumption) สำหรับแต่ละเขต
# โดยการรวมค่าทั้งหมดในแต่ละคอลัมน์ของเขต
total_consumption_by_district = df_elec[district_cols].sum().reset_index()
total_consumption_by_district.columns = ['District', 'Total_Consumption']

# 3. คำนวณอัตราการเติบโต (Growth Rate) สำหรับแต่ละเขต
# ใช้ข้อมูลจากปีแรก (2562) และปีสุดท้าย (2567) ที่เป็นปีเต็ม

# ตรวจสอบปีที่มีข้อมูลก่อน
years_in_data = df_elec['ปี'].unique()
start_year_buddhist = years_in_data.min()
end_year_buddhist = years_in_data.max()

# ถ้าปีสุดท้ายมีข้อมูลไม่ครบเดือน อาจใช้ปีก่อนหน้า หรือใช้ max เพื่อให้ได้ข้อมูลล่าสุด
# ในกรณีนี้เราจะใช้ปีแรก 2562 (2019) และปีสุดท้าย 2567 (2024) เนื่องจากปี 2568 อาจไม่เต็มปี
consumption_2562 = df_elec[df_elec['ปี'] == start_year_buddhist][district_cols].sum()
consumption_2567 = df_elec[df_elec['ปี'] == 2567][district_cols].sum()

growth_rate_by_district = ((consumption_2567 - consumption_2562) / consumption_2562) * 100
growth_rate_by_district = growth_rate_by_district.reset_index()
growth_rate_by_district.columns = ['District', 'Growth_Rate']

# 4. รวมข้อมูล Total Consumption และ Growth Rate เข้าด้วยกัน
df_district_analysis = pd.merge(total_consumption_by_district, growth_rate_by_district, on='District')

print('✅ ข้อมูลสำหรับการวิเคราะห์เขตเสร็จสมบูรณ์แล้ว')
print('\n🔍 ตัวอย่างข้อมูลวิเคราะห์แต่ละเขต:')
display(df_district_analysis.head())

# 5. สร้างกราฟ Scatter Plot
fig = px.scatter(
    df_district_analysis,
    x='Total_Consumption',
    y='Growth_Rate',
    text='District',
    size='Total_Consumption', # ขนาดของจุดแสดงตามปริมาณการใช้ไฟฟ้า
    color='District', # แยกสีตามเขต
    title='ปริมาณการใช้ไฟฟ้าและอัตราการเติบโตของแต่ละเขต (พ.ศ. 2562 - 2567)',
    labels={
        'Total_Consumption': 'ปริมาณการใช้ไฟฟ้าทั้งหมด (GWh)',
        'Growth_Rate': '''อัตราการเติบโต (%)
        (พ.ศ. 2562 เทียบ พ.ศ. 2567)'''
    },
    height=600
)

fig.update_traces(textposition='top center')
fig.update_layout(hovermode="x unified")
fig.show()

✅ ข้อมูลสำหรับการวิเคราะห์เขตเสร็จสมบูรณ์แล้ว

🔍 ตัวอย่างข้อมูลวิเคราะห์แต่ละเขต:

   District  Total_Consumption  Growth_Rate
0  วัดเลียบ            7427.11    -4.219526
1   คลองเตย           30410.76     3.361444
2   ยานนาวา           13106.78     1.726970
3   บางกะปิ           21881.92     8.809913
4   มีนบุรี           14816.11    12.440470

จากกราฟ Scatter Plot 'ปริมาณการใช้ไฟฟ้าและอัตราการเติบโตของแต่ละเขต (พ.ศ. 2562 - 2567)' เราสามารถระบุเขตต่างๆ ได้ดังนี้ครับ:

**1. เขตที่ใช้ไฟฟ้ามากและยังมีการเติบโตต่อเนื่อง (High Consumption & Growing):**

*   **บางพลี:** เป็นเขตที่มีปริมาณการใช้ไฟฟ้าทั้งหมดสูงที่สุดในบรรดาเขตทั้งหมด (อยู่ที่ประมาณ 36,452 GWh) และยังคงมีอัตราการเติบโตที่เป็นบวก (ประมาณ 6.68%) แสดงให้เห็นว่าเป็นเขตที่มีกิจกรรมทางเศรษฐกิจสูงและยังคงขยายตัว
*   **คลองเตย, นนทบุรี, สามเสน, บางเขน, บางนา:** เขตเหล่านี้มีปริมาณการใช้ไฟฟ้าที่สูงเช่นกัน และมีอัตราการเติบโตที่เป็นบวก แสดงให้เห็นถึงการขยายตัวทางเศรษฐกิจอย่างต่อเนื่อง

**2. เขตที่ใช้ไฟฟ้าน้อยแต่มีอัตราการเติบโตที่รวดเร็ว (Low Consumption & Fast Growing):**

*   **บางบัวทอง:** เป็นเขตที่มีปริมาณการใช้ไฟฟ้าไม่สูงมากนัก (ประมาณ 13,321 GWh) แต่มีอัตราการเติบโตที่โดดเด่นและสูงที่สุด (ประมาณ 28.91%) บ่งชี้ว่าเขตนี้มีการพัฒนาอย่างรวดเร็วและมีศักยภาพในการขยายตัวสูงในอนาคต
*   **บางใหญ่, มีนบุรี, ลาดกระบัง, ธนบุรี:** เขตเหล่านี้มีปริมาณการใช้ไฟฟ้าอยู่ในระดับปานกลางถึงน้อย แต่มีอัตราการเติบโตที่ค่อนข้างสูง (ตั้งแต่ประมาณ 9% ถึง 17%) ซึ่งแสดงถึงการพัฒนาและขยายตัวของพื้นที่เหล่านั้นครับ

**ข้อสังเกตเพิ่มเติม:** บางเขตอย่างเช่น สมุทรปราการ และ ราษฎร์บูรณะ แม้จะมีปริมาณการใช้ไฟฟ้าสูง แต่กลับมีอัตราการเติบโตที่เป็นลบ ซึ่งอาจบ่งชี้ถึงความท้าทายหรือการชะลอตัวทางเศรษฐกิจในพื้นที่นั้นๆ ครับ

### 🔎3. รูปแบบการใช้ไฟฟ้าตามฤดูกาลต่างกันระหว่างเขตไหม?

จากกราฟข้อมูลรายเดือนของทุกเขตด้านล่าง สังเกตได้ถึงสิ่งเหล่านี้:

1.  **ปริมาณการใช้ไฟฟ้า**: เเต่ละเขตมีการใช้ปริมาณมากน้อยเเค่ไหน ในช่วงเวลาไหนบ้าง?
2.  **อัตราการเติบโตของการใช้ไฟฟ้า**: เเต่ละเขตมีอัตราการเติบโตของการใช้ไฟฟ้าที่มากขึ้น หรือน้อยลงโดยเปรียบเทียบปีแรก (2562) และปีสุดท้าย (2567) ที่ข้อมูลครบล่าสุด จากการใช้ไฟฟ้าทั้งหมดของเเต่ละเขต

In [9]:
# 1. เตรียมข้อมูลสำหรับวิเคราะห์รูปแบบฤดูกาล
# เลือกเฉพาะคอลัมน์ที่เกี่ยวข้องกับการใช้ไฟฟ้าของแต่ละเขตและคอลัมน์ 'Month_num'
df_seasonal = df_elec[['Month_num'] + district_cols]

# Group by 'Month_num' และคำนวณค่าเฉลี่ยการใช้ไฟฟ้าสำหรับแต่ละเขตในแต่ละเดือน
df_seasonal_avg = df_seasonal.groupby('Month_num')[district_cols].mean().reset_index()

# แปลงข้อมูลจาก wide format เป็น long format เพื่อใช้กับ Plotly Express ได้ง่ายขึ้น
df_seasonal_avg_melted = df_seasonal_avg.melt(id_vars='Month_num', var_name='District', value_name='Average_Consumption')

# สร้างชื่อเดือนภาษาไทยเพื่อแสดงผลบนกราฟ
month_names = {
    1: 'ม.ค.', 2: 'ก.พ.', 3: 'มี.ค.', 4: 'เม.ย.', 5: 'พ.ค.', 6: 'มิ.ย.',
    7: 'ก.ค.', 8: 'ส.ค.', 9: 'ก.ย.', 10: 'ต.ค.', 11: 'พ.ย.', 12: 'ธ.ค.'
}
df_seasonal_avg_melted['Month'] = df_seasonal_avg_melted['Month_num'].map(month_names)

print('✅ ข้อมูลรูปแบบฤดูกาลเฉลี่ยต่อเดือนของแต่ละเขตสำเร็จแล้ว')
print('\n🔍 ตัวอย่างข้อมูล:')
display(df_seasonal_avg_melted.head())

# 2. สร้างกราฟเส้นเพื่อเปรียบเทียบรูปแบบฤดูกาล
fig = px.line(
    df_seasonal_avg_melted,
    x='Month',
    y='Average_Consumption',
    color='District',
    line_group='District',
    title='รูปแบบฤดูกาลของการใช้ไฟฟ้าเฉลี่ยรายเดือนของแต่ละเขต',
    labels={
        'Month': 'เดือน',
        'Average_Consumption': 'ปริมาณการใช้ไฟฟ้าเฉลี่ย (GWh)',
        'District': 'เขต'
    },
    height=600,
    hover_name='District'
)

fig.update_xaxes(categoryorder='array', categoryarray=list(month_names.values()))
fig.update_layout(hovermode="closest")
fig.show()

✅ ข้อมูลรูปแบบฤดูกาลเฉลี่ยต่อเดือนของแต่ละเขตสำเร็จแล้ว

🔍 ตัวอย่างข้อมูล:

   Month_num  District  Average_Consumption  Month
0          1  วัดเลียบ            83.307143   ม.ค.
1          2  วัดเลียบ            84.820000   ก.พ.
2          3  วัดเลียบ            93.304286  มี.ค.
3          4  วัดเลียบ            93.761429  เม.ย.
4          5  วัดเลียบ            96.852857   พ.ค.

จากกราฟเส้น 'รูปแบบฤดูกาลของการใช้ไฟฟ้าเฉลี่ยรายเดือนของแต่ละเขต' ที่สร้างไว้ เราสามารถระบุลักษณะการใช้ไฟฟ้าตามฤดูกาลของแต่ละเขต พร้อมตั้งสมมติฐานได้ดังนี้ครับ:

**1. เขตที่มีความผันผวนตามฤดูกาลสูงผิดปกติ:**

*   **เขตที่สังเกตได้ชัด:** เขตที่มีกราฟพุ่งสูงขึ้นอย่างเห็นได้ชัดในช่วงเดือนมีนาคม-พฤษภาคม และลดลงในช่วงเดือนอื่น ๆ ได้แก่ **บางพลี, สมุทรปราการ, ลาดกระบัง, บางขุนเทียน, บางนา, มีนบุรี, บางใหญ่, บางบัวทอง** (โดยเฉพาะบางพลีและสมุทรปราการจะมีปริมาณการใช้สูงที่สุดและมีรูปแบบคล้ายกัน)
*   **ลักษณะการใช้พลังงานแบบใด:**
    *   **สมมติฐาน: เขตอุตสาหกรรม/พาณิชยกรรม และที่อยู่อาศัยที่หนาแน่น** การที่การใช้ไฟฟ้าพุ่งสูงขึ้นในช่วงหน้าร้อน (มี.ค.-พ.ค.) อย่างมีนัยสำคัญ บ่งชี้ถึงการใช้เครื่องปรับอากาศจำนวนมากในภาคครัวเรือนและภาคธุรกิจ นอกจากนี้ในเขตอุตสาหกรรมที่ต้องมีการควบคุมอุณหภูมิในกระบวนการผลิต อาจมีการใช้ไฟฟ้าเพิ่มขึ้นในฤดูร้อนเช่นกัน เขตเหล่านี้อาจมีโรงงาน สถานประกอบการขนาดใหญ่ หรือแหล่งที่อยู่อาศัยที่มีการใช้เครื่องปรับอากาศจำนวนมาก

**2. เขตที่มีการใช้ไฟฟ้าคงที่ตลอดปี:**

*   **เขตที่สังเกตได้ชัด:** เขตที่กราฟค่อนข้างแบนราบ ไม่มีความผันผวนขึ้นลงตามฤดูกาลมากนัก แต่ยังคงมีปริมาณการใช้ไฟฟ้าค่อนข้างสูง ได้แก่ **คลองเตย, ยานนาวา, สามเสน, วัดเลียบ, ธนบุรี, ราษฎร์บูรณะ, นนทบุรี, บางกะปิ**
*   **ลักษณะการใช้พลังงานแบบใด:**
    *   **สมมติฐาน: เขตพาณิชยกรรม/ธุรกิจ/ราชการ/ที่อยู่อาศัยแบบตึกสูง** เขตเหล่านี้มักเป็นศูนย์กลางธุรกิจ, ออฟฟิศ, ห้างสรรพสินค้า, โรงพยาบาล หรืออาคารที่พักอาศัยขนาดใหญ่ที่มีการใช้ไฟฟ้าต่อเนื่องตลอดทั้งปี ไม่ว่าจะฤดูไหนก็ตาม การใช้เครื่องปรับอากาศในอาคารเหล่านี้อาจถูกควบคุมในระดับหนึ่ง หรือมีระบบระบายความร้อนที่ประสิทธิภาพสูง ทำให้ความต้องการไฟฟ้าไม่ผันผวนตามอุณหภูมิภายนอกมากนักเมื่อเทียบกับเขตที่เน้นที่อยู่อาศัยทั่วไป หรืออุตสาหกรรมที่อ่อนไหวต่ออุณหภูมิ